SELECT * FROM overtime_analysis oa WHERE (TO_DATE(oa.attendance_date, 'DD/MM/YYYY') BETWEEN TO_DATE('07/01/2024', 'DD/MM/YYYY') AND TO_DATE('10/01/2024', 'DD/MM/YYYY')) 
AND (oa.organization_name IS NULL OR oa.organization_name = 'Adax Security Systems')
AND (oa.branch_name IS NULL OR oa.branch_name = 'Qatar') 
AND (oa.department_name IS NULL OR oa.department_name = 'Technical')
AND (oa.category_name IS NULL OR oa.category_name = 'Support')
AND (oa.designation_name IS NULL OR oa.designation_name = 'Support Engineer')
AND (oa.grade_name IS NULL OR oa.grade_name = 'Grade-1')
AND (oa.section_name IS NULL OR oa.section_name = 'Support Team')
AND (oa.project_name IS NULL OR oa.project_name = 'MEKHANIS CDD AND POLICE STATIO')
AND (oa.phase_name IS NULL OR oa.phase_name = 'MEKHANIS CDD AND POLICE STATIO')
AND (oa.job_name IS NULL OR oa.job_name = 'MEKHANIS CDD AND POLICE STATIO')
AND (oa.user_name IS NULL OR oa.user_name = 'Vaishak Chembalipurath')   
